"""drop_session_id

迁移 ID: 776610dfef16
父迁移: a0da24e5a4e0
创建时间: 2024-10-27 14:15:07.490830

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "776610dfef16"
down_revision: str | Sequence[str] | None = "a0da24e5a4e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_memes_memegenerationrecord", schema=None
    ) as batch_op:
        batch_op.drop_column("session_persist_id")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_memes_memegenerationrecord", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column("session_persist_id", sa.INTEGER(), nullable=False)
        )
    # ### end Alembic commands ###
