"""add_uninfo_id

迁移 ID: a0749ed48096
父迁移: a82b5f32c60f
创建时间: 2024-10-27 13:52:41.377360

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a0749ed48096"
down_revision: str | Sequence[str] | None = "a82b5f32c60f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_memes_memegenerationrecord", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("uninfo_persist_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_memes_memegenerationrecord", schema=None
    ) as batch_op:
        batch_op.drop_column("uninfo_persist_id")
    # ### end Alembic commands ###
