"""uninfo_id_not_none

迁移 ID: a0da24e5a4e0
父迁移: 0be9a1f9a444
创建时间: 2024-10-27 14:13:40.034714

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a0da24e5a4e0"
down_revision: str | Sequence[str] | None = "0be9a1f9a444"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_memes_memegenerationrecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "uninfo_persist_id", existing_type=sa.INTEGER(), nullable=False
        )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_memes_memegenerationrecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "uninfo_persist_id", existing_type=sa.INTEGER(), nullable=True
        )
    # ### end Alembic commands ###
